export const PHOTOBOOTH_CAMERA_SNAPPED = "PHOTOBOOTH_CAMERA#SNAPPED";
export const PHOTOBOOTH_AVAILABLE_CAMERAS_UPDATED = "PHOTOBOOTH_CAMERA#AVAILABLE_CAMERAS_UPDATED";
export const PHOTOBOOTH_CAMERA_SINGLES_SNAPPED = "PHOTOBOOTH_CAMERA#SINGLES_SNAPPED";
export const PHOTOBOOTH_CAMERA_DOUBLE_CLICK = "PHOTOBOOTH_CAMERA#DBLCLICK";